routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('berita-sekolah', 'BeritaSekolahController');
    Route::resource('berita-pendidikan', 'BeritaPendidikanController');
    Route::resource('profile', 'ProfileController');
//    Route::resource('event', 'EventController');

    // Route::get('profile', 'ProfileController')->name('profile.index');
    // Route::get('event', 'EventController')->name('event.test');

    Route::get('setting', 'SettingController@index')->name('setting.index');
    Route::get('setting/{id}/edit', 'SettingController@edit')->name('setting.edit');
    Route::patch('setting/{id}', 'SettingController@update')->name('setting.update');

    Route::get('hero/{id}/edit', 'SettingController@heroEdit')->name('hero.edit');
    Route::patch('hero/{id}', 'SettingController@heroUpdate')->name('hero.update');
});

app/Models/BeritaPendidikan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class BeritaPendidikan extends Model
{
    protected $fillable = ['title', 'content', 'image', 'user_id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/BeritaPendidikanController.php
<?php

namespace App\Http\Controllers\Admin;

use File;
use Illuminate\Http\Request;
use App\Models\BeritaPendidikan;
use App\Http\Controllers\Controller;

class BeritaPendidikanController extends Controller
{
    public function index()
    {
        $rows = BeritaPendidikan::all();
        return view('admin.beritaPendidikan.index', compact('rows'));
    }

    public function create()
    {
        return view('admin.beritaPendidikan.create');
    }

    public function store()
    {
        $this->validate(request(), [
            'title'     => 'required',
            'image'     => 'required|mimes:jpeg,jpg,png',
            'content'   => 'required',
        ]);

        $row = new BeritaPendidikan;
        $row->title = request('title');

        # Processing Image
        $file       = request()->file('image');
        $fileName   = rand(10000, 99999).'-'.$file->getClientOriginalName();
        request()->file('image')->move('image/', $fileName);

        $row->image = $fileName;
        $row->content = request('content');
        $row->user_id = auth()->user()->id;
        $row->save();

        flash('Create data success.')->success();
        return redirect()->route('admin.berita-pendidikan.index');
    }

    public function edit($id)
    {
        $row = BeritaPendidikan::find($id);
        return view('admin.beritaPendidikan.edit', compact('row'));
    }

    public function update($id)
    {
        $row = BeritaPendidikan::find($id);
        $row->title = request('title');

        # Processing Image
        if(!is_null(request()->file('image'))) {
            $file = 'image/'.$row->image;
            File::delete($file);

            $file       = request()->file('image');
            $fileName   = rand(10000, 99999).'-'.$file->getClientOriginalName();
            request()->file('image')->move('image/', $fileName);

            $row->image = $fileName;
        }

        $row->content = request('content');
        $row->user_id = auth()->user()->id;
        $row->update();

        flash('Update Success.')->success();
        return redirect()->route('admin.berita-pendidikan.index');
    }

    public function destroy($id)
    {
        $row = BeritaPendidikan::find($id);

        # Delete Image
        $file = 'image/'.$row->image;
        File::delete($file);

        $row->delete();
        flash('Delete Success.')->warning();
        return redirect()->route('admin.berita-pendidikan.index');
    }
}

resources/views/admin/beritaPendidikan/create.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Create Berita Pendidikan
        </div>

        @include('errors.session_error')

        <div class="panel-body">
            <form action="{{ route('admin.berita-pendidikan.store') }}" method="post" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group">
                    <div class="col-md-6">
                        <label for="title">Title</label>
                        <input type="text" name="title" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <label for="image">Image Cover</label>
                        <input type="file" name="image" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <label for="content">Content</label>
                        <textarea name="content" id="summernote" cols="5" rows="5"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="text-center pull-right">
                            <button class="btn btn-success" type="submit"> Submit </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
@endsection

@section('scripts')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
       $(document).ready(function() {
           $('#summernote').summernote();
       });
    </script>
@endsection

resources/views/admin/beritaPendidikan/edit.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Create Berita Pendidikan
        </div>

        @include('errors.session_error')

        <div class="panel-body">
            <form action="{{ route('admin.berita-pendidikan.update', $row->id) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-group">
                    <div class="col-md-6">
                        <label for="title">Title</label>
                        <input type="text" name="title" class="form-control" value="{{ old('title', $row->title) }}">
                    </div>
                    <div class="col-md-6">
                        <label for="image">Image Cover</label>
                        <img src="{{ asset('image/'.$row->image) }}" class="img-responsive" style="max-width: 300px; max-height: 300px">
                        <input type="file" name="image" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <label for="content">Content</label>
                        <textarea name="content" id="summernote" cols="5" rows="5">{{ old('content', $row->content) }}</textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="text-center pull-right">
                            <button class="btn btn-success" type="submit"> Update </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
@endsection

@section('scripts')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
       $(document).ready(function() {
           $('#summernote').summernote();
       });
    </script>
@endsection

resources/views/admin/beritaPendidikan/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Berita Pendidikan
        </div>
        <div class="panel-body">
            <table class="table table-responsive table-bordered table-hovered">
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Image</th>
                    <th>Share social</th>
                    <th colspan="2">Action</th>
                </tr>
                @forelse($rows as $row)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $row->title }}</td>
                    <td><img src="{{ asset('image/'.$row->image) }}" class="img-responsive" style="max-height: 200px; max-width: 200px"></td>
                    <td>
                      <div id="social-links">
                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ config('app.url').'/'.str_slug($row->title) }}" class="social-button btn btn-default btn-xs" id="">
                            <span class="fa fa-facebook"></span>
                        </a>
                        <a href="https://twitter.com/intent/tweet?text=Hello, please take a look.&url={{ config('app.url').'/'.str_slug($row->title) }}" class="social-button btn btn-default btn-xs" id="">
                            <span class="fa fa-twitter"></span>
                        </a>
                        <a href="https://plus.google.com/share?url={{ config('app.url').'/'.str_slug($row->title) }}" class="social-button btn btn-default btn-xs" id="">
                            <span class="fa fa-google-plus"></span>
                        </a>
                        <a href="http://www.linkedin.com/shareArticle?mini=true&url={{ config('app.url').'/'.str_slug($row->title) }}&title=Hello, please take a look.&summary=" class="social-button btn btn-default btn-xs" id="">
                            <span class="fa fa-linkedin"></span>
                        </a>
                      </div>
                    </td>
                    <td>
                        <a href="{{ route('admin.berita-pendidikan.edit', $row->id) }}" class="btn btn-info">Edit</a>
                    </td>
                    <td>
                        <form action="{{ route('admin.berita-pendidikan.destroy', $row->id) }}" method="POST">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5">Click <a href="{{ route('admin.berita-pendidikan.create') }}">here</a> to create new berita pendidikan.</td>
                </tr>
                @endforelse
            </table>
        </div>
@endsection