routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['namespace' => 'Admin', 'as' => 'admin.', 'prefix' => 'admin'], function () {
    Route::resource('berita-sekolah', 'BeritaSekolahController');
    Route::resource('berita-pendidikan', 'BeritaPendidikanController');
    Route::resource('profile', 'ProfileController');
//    Route::resource('event', 'EventController');

    // Route::get('profile', 'ProfileController')->name('profile.index');
    // Route::get('event', 'EventController')->name('event.test');

    Route::get('setting', 'SettingController@index')->name('setting.index');
    Route::get('setting/{id}/edit', 'SettingController@edit')->name('setting.edit');
    Route::patch('setting/{id}', 'SettingController@update')->name('setting.update');

    Route::get('hero/{id}/edit', 'SettingController@heroEdit')->name('hero.edit');
    Route::patch('hero/{id}', 'SettingController@heroUpdate')->name('hero.update');
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    protected $fillable = ['key', 'value', 'icon'];
}

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Setting;
use App\Models\MasterHero;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SettingController extends Controller
{
    public function index()
    {
        $rows = Setting::all();
        $heroes = MasterHero::all();
        return view('admin.setting.index', compact('rows', 'heroes'));
    }

    public function edit($id)
    {
        $row = Setting::find($id);
        return view('admin.setting.edit', compact('row'));
    }

    public function update($id)
    {
        $row = Setting::find($id);
        $row->value = request('value');
        $row->save();

        flash('Edit data success.')->success();
        return redirect()->route('admin.setting.index');
    }

    public function heroEdit($id)
    {
        $row = MasterHero::find($id);
        return view('admin.setting.edit-hero', compact('row'));
    }

    public function heroUpdate($id)
    {
        $row = MasterHero::find($id);
        # Processing Image
        if(!is_null(request()->file('image'))) {
            // $file = $row->image;
            // File::delete($file);

            $file       = request()->file('image');
            $fileName   = rand(10000, 99999).'-'.$file->getClientOriginalName();
            request()->file('image')->move('img/', $fileName);

            $row->value = 'img/'.$fileName;
        }
        $row->save();

        flash('Edit data success.')->success();
        return redirect()->route('admin.setting.index');
    }
}

resources/views/admin/setting/edit-hero.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Edit Form
        </div>

        @include('errors.session_error')

        <div class="panel-body">
            <form action="{{ route('admin.hero.update', $row->id) }}" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-group">
                    <div class="col-md-6">
                        <label for="value">Image</label>
                        <img src="{{ asset($row->value) }}" class="img-responsive" style="max-width: 300px; max-height: 300px">
                        <input type="file" name="image" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="text-center pull-right">
                            <button class="btn btn-success" type="submit"> Update </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
@endsection

@section('scripts')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
       $(document).ready(function() {
           $('#summernote').summernote();
       });
    </script>
@endsection

resources/views/admin/setting/edit.blade.php
@extends('layouts.admin')

@section('styles')
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.css" rel="stylesheet">
@endsection

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Edit Form
        </div>

        @include('errors.session_error')

        <div class="panel-body">
            <form action="{{ route('admin.setting.update', $row->id) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}
                <div class="form-group">
                    <div class="col-md-8 col-md-offset-2">
                        <label for="value">Value</label>
                        <input type="text" name="value" class="form-control" value="{{ old('value', $row->value) }}">
                    </div>
                    <br>
                    <button class="btn btn-success" type="submit" style="margin-top: 4px"> Update </button>
                </div>
            </form>
        </div>
@endsection

@section('scripts')
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.8/summernote.js"></script>
    <script>
       $(document).ready(function() {
           $('#summernote').summernote();
       });
    </script>
@endsection

resources/views/admin/setting/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="panel panel-primary">
        <div class="panel-heading text-center">
            Master Setting
        </div>
        <div class="panel-body">
            <table class="table table-responsive table-bordered table-hovered">
                <tr>
                    <th>#</th>
                    <th>Key</th>
                    <th>Value</th>
                    <th>Action</th>
                </tr>
                @foreach($rows as $row)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $row->key }}</td>
                    <td>{{ $row->value }}</td>
                    <td>
                        <a href="{{ route('admin.setting.edit', $row->id) }}" class="btn btn-info">Edit</a>
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
    <div class="panel panel-danger">
        <div class="panel-heading text-center">
            Hero Banner
        </div>
        <div class="panel-body">
            <table class="table table-responsive table-bordered table-hovered">
                <tr>
                    <th>#</th>
                    <th>Key</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
                @foreach($heroes as $hero)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $hero->key }}</td>
                    <td><img src="{{ asset($hero->value) }}" class="img-responsive" style="max-height: 300px; max-height: 300px"></td>
                    <td>
                        <a href="{{ route('admin.hero.edit', $hero->id) }}" class="btn btn-info">Edit</a>
                    </td>
                </tr>
                @endforeach
            </table>
        </div>
    </div>
@endsection